// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRFk85mfMyUjFNMfdqyLXbe9Qh9XPL7Rc',
    appId: '1:394583381706:web:f169e55be54c562da90633',
    messagingSenderId: '394583381706',
    projectId: 'ai4good-faf8f',
    authDomain: 'ai4good-faf8f.firebaseapp.com',
    storageBucket: 'ai4good-faf8f.firebasestorage.app',
    measurementId: 'G-9TSD9KM15C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhHBKCiuJK_3BoFn464CLXnkw2xoUxNTA',
    appId: '1:394583381706:android:74d9c57f968cdd58a90633',
    messagingSenderId: '394583381706',
    projectId: 'ai4good-faf8f',
    storageBucket: 'ai4good-faf8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Q_bKazq3PdgtCioVgGNTCeGLYAwajD0',
    appId: '1:394583381706:ios:f43de945399a8309a90633',
    messagingSenderId: '394583381706',
    projectId: 'ai4good-faf8f',
    storageBucket: 'ai4good-faf8f.firebasestorage.app',
    iosBundleId: 'com.example.ai4good',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Q_bKazq3PdgtCioVgGNTCeGLYAwajD0',
    appId: '1:394583381706:ios:f43de945399a8309a90633',
    messagingSenderId: '394583381706',
    projectId: 'ai4good-faf8f',
    storageBucket: 'ai4good-faf8f.firebasestorage.app',
    iosBundleId: 'com.example.ai4good',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRFk85mfMyUjFNMfdqyLXbe9Qh9XPL7Rc',
    appId: '1:394583381706:web:4cc8730c9166be01a90633',
    messagingSenderId: '394583381706',
    projectId: 'ai4good-faf8f',
    authDomain: 'ai4good-faf8f.firebaseapp.com',
    storageBucket: 'ai4good-faf8f.firebasestorage.app',
    measurementId: 'G-MS7Y8VM9B2',
  );
}
